using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using Forged.Generator.Helpers;
using Forged.Generator.Models;

namespace Forged.Generator;

[Generator]
public class ForgedGenerator : IIncrementalGenerator
{
	private const string Header = // lang=cs
		$"""
		 //----------------------------------------------------------------------------
		 // <auto-generated>
		 //	This code was generated by {ThisAssembly.PackageId}
		 //	Runtime version: {ThisAssembly.PackageVersion}
		 //
		 //    Changes to this file may cause incorrect behavior and will be lost if
		 //    the code is regenerated.
		 //</auto-generated>
		 //----------------------------------------------------------------------------
		 """;

	private const string Attributes = // lang=cs
		$"""
		 [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
		 [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
		 [global::System.CodeDom.Compiler.GeneratedCode("{ThisAssembly.Title}", "{ThisAssembly.Version}")]
		 """;

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var typesToFake = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				"Forged.Core.FakeAttribute",
				predicate: static (s, _) => s is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax,
				transform: static (ctx, _) => GetFakedTypes(ctx.SemanticModel, ctx.TargetNode)
			)
			.Where(static m => m is not null)
			.Select(static (m, _) => m!)
			.Collect();

		var fakersToGenerate = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				"Forged.Core.FakerAttribute`1",
				predicate: static (s, _) => s is ClassDeclarationSyntax,
				transform: static (ctx, _) => GetFakers(ctx.SemanticModel, ctx.TargetNode)
			)
			.Where(static m => m is not null)
			.Select(static (m, _) => m!)
			.Collect();
		
		var combined = typesToFake
			.Combine(fakersToGenerate);

		context.RegisterSourceOutput(combined, static (spc, source) => {
			var (types, fakers) = source;
			foreach (var ttg in types.Concat(fakers))
			{
				Execute(spc, ttg);
			}
		});
	}

	private static TypeToGenerate? GetFakedTypes(SemanticModel semanticModel, SyntaxNode node)
	{
		if (semanticModel.GetDeclaredSymbol(node) is not INamedTypeSymbol symbol)
		{
			return null;
		}

		var properties = symbol.GetMembers()
			.OfType<IPropertySymbol>()
			.Where(p => p.SetMethod is not null && p.DeclaredAccessibility == Accessibility.Public)
			.Select(p => new PropertyToGenerate(
				Name: p.Name,
				Type: p.Type.ToDisplayString(),
				IsRequired: p.IsRequired
			))
			.ToList();

		return new TypeToGenerate(
			Namespace: symbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : symbol.ContainingNamespace.ToDisplayString(),
			Name: symbol.Name,
			Properties: properties.ToEquatableReadOnlyList()
		);
	}
	
	private static TypeToGenerate? GetFakers(SemanticModel semanticModel, SyntaxNode node)
	{
		if (semanticModel.GetDeclaredSymbol(node) is not INamedTypeSymbol symbol)
		{
			return null;
		}
		
		var attribute = symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "FakerAttribute");
		if (attribute is not { AttributeClass: { IsGenericType: true, TypeArguments: [ INamedTypeSymbol targetType ] }  })
		{
			return null;
		}
		
		var properties = targetType.GetMembers()
			.OfType<IPropertySymbol>()
			.Where(p => p.SetMethod is not null && p.DeclaredAccessibility == Accessibility.Public)
			.Select(p => new PropertyToGenerate(
				Name: p.Name,
				Type: p.Type.ToDisplayString(),
				IsRequired: p.IsRequired
			))
			.ToList();

		return new TypeToGenerate(
			Namespace: targetType.ContainingNamespace.IsGlobalNamespace ? string.Empty : targetType.ContainingNamespace.ToDisplayString(),
			Name: targetType.Name,
			Properties: properties.ToEquatableReadOnlyList(),
			FakerName: symbol.Name
		);
	}

	private static void Execute(SourceProductionContext context, TypeToGenerate typeToGenerate)
	{
		var w = new IndentedWriter();
		w.WriteLine(Header);
		w.WriteLine("#nullable enable");
		
		var fakerName = typeToGenerate.FakerName ?? $"{typeToGenerate.Name}Faker";
		
		if (!string.IsNullOrEmpty(typeToGenerate.Namespace))
		{
			w.WriteLine();
			w.WriteLine($"namespace {typeToGenerate.Namespace};");
		}

		w.WriteLine();
		w.WriteLine(Attributes);

		w.WriteLine($"public partial class {fakerName} : global::Forged.Core.Faker<{typeToGenerate.Name}>");
		w.BodyBlock(() => {

			foreach (var prop in typeToGenerate.Properties)
			{
				w.Write("public ");
				if (prop.IsRequired)
				{
					w.Write("required ");
				}
				w.Write($"virtual global::System.Func<global::Forged.Core.Forge, global::Forged.Core.Generators.IGenerator<{prop.Type}>>");
				if (!prop.IsRequired)
				{
					w.Write("?");
				}
				w.WriteLine($" {prop.Name} {{ get; init; }}");
			}

			w.WriteLine();
			w.WriteLine("// Constructor");
			w.WriteLine($"public {fakerName}(global::System.Random? random = null, global::System.Globalization.CultureInfo? locale = null) : base(random, locale) {{ }}");

			w.WriteLine();
			w.WriteLine($"public override {typeToGenerate.Name} Get()");
			w.BodyBlock(() => {

				foreach (var prop in typeToGenerate.Properties)
				{
					w.Write($"var {Decapitalize(prop.Name)}Generator = {prop.Name}");
					w.WriteLine(prop.IsRequired
						? "(this.Forge);"
						: "?.Invoke(this.Forge);");
				}

				w.WriteLine();
				w.WriteLine($"return new {typeToGenerate.Name}");
				w.InitBlock(() => {
					foreach (var prop in typeToGenerate.Properties)
					{
						w.Write($"{prop.Name} = {Decapitalize(prop.Name)}Generator");
						w.WriteLine(prop.IsRequired
							? ".Generate(),"
							: "?.Generate() ?? default!,");
					}
				});
			});
		});
		
		context.AddSource($"{fakerName}.g.cs", SourceText.From(w.ToString(), Encoding.UTF8));
	}

	private static string Decapitalize(string input)
	{
		var span = input.AsSpan();
		Span<char> result = stackalloc char[span.Length];
		result[0] = char.ToLowerInvariant(span[0]);
		span[1..].CopyTo(result[1..]);
		return result.ToString();
	}
}