using System.Diagnostics.CodeAnalysis;
using System.Text;
using Forged.Generator.Helpers;
using Forged.Generator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Forged.Generator;

[Generator]
public class ForgedGenerator : IIncrementalGenerator
{
	private const string Header = // lang=cs
		$"""
		 //----------------------------------------------------------------------------
		 // <auto-generated>
		 //	This code was generated by {ThisAssembly.PackageId}
		 //	Runtime version: {ThisAssembly.PackageVersion}
		 //
		 //    Changes to this file may cause incorrect behavior and will be lost if
		 //    the code is regenerated.
		 //</auto-generated>
		 //----------------------------------------------------------------------------
		 """;

	private const string Attributes = // lang=cs
		$"""
		 [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
		 [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
		 [global::System.CodeDom.Compiler.GeneratedCode("{ThisAssembly.Title}", "{ThisAssembly.Version}")]
		 """;

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var typesToFake = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				"Forged.Core.FakeAttribute",
				predicate: static (s, _) => s is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax,
				transform: static (ctx, _) => GetFakedTypes(ctx.SemanticModel, ctx.TargetNode)
			)
			.Where(static m => m is not null)
			.Select(static (m, _) => m!)
			.Collect();

		var fakersToGenerate = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				"Forged.Core.FakerAttribute`1",
				predicate: static (s, _) => s is ClassDeclarationSyntax,
				transform: static (ctx, _) => GetFakers(ctx.SemanticModel, ctx.TargetNode)
			)
			.Where(static m => m is not null)
			.Select(static (m, _) => m!)
			.Collect();
		
		var combined = typesToFake
			.Combine(fakersToGenerate);

		context.RegisterSourceOutput(combined, static (spc, source) => {
			var (types, fakers) = source;
			var allTypes = types.Concat(fakers).ToArray();
			foreach (var ttg in allTypes)
			{
				Execute(spc, ttg);
			}

			foreach (var group in allTypes.GroupBy(static ttg => ttg.Namespace))
			{
				var models = group
					.GroupBy(static ttg => ttg.Name)
					.Select(static nested => nested.First())
					.ToArray();
				ExecuteGenerated(spc, group.Key, models);
			}
		});
	}

	private static TypeToGenerate? GetFakedTypes(SemanticModel semanticModel, SyntaxNode node)
	{
		if (semanticModel.GetDeclaredSymbol(node) is not INamedTypeSymbol symbol) return NoTypeToGenerate();

		var properties = symbol.GetMembers()
			.OfType<IPropertySymbol>()
			.Where(p => p.SetMethod is not null && p.DeclaredAccessibility == Accessibility.Public)
			.Select(p => new PropertyToGenerate(
				Name: p.Name,
				Type: p.Type.ToDisplayString(),
				IsRequired: p.IsRequired
			))
			.ToList();

		return new TypeToGenerate(
			Namespace: symbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : symbol.ContainingNamespace.ToDisplayString(),
			Name: symbol.Name,
			Properties: properties.ToEquatableReadOnlyList()
		);
	}
	
	private static TypeToGenerate? GetFakers(SemanticModel semanticModel, SyntaxNode node)
	{
		if (semanticModel.GetDeclaredSymbol(node) is not INamedTypeSymbol symbol) return NoTypeToGenerate();
		
		var attribute = symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "FakerAttribute");
		if (attribute is not { AttributeClass: { IsGenericType: true, TypeArguments: [ INamedTypeSymbol targetType ] } }) return NoTypeToGenerate();
		
		var properties = targetType.GetMembers()
			.OfType<IPropertySymbol>()
			.Where(p => p.SetMethod is not null && p.DeclaredAccessibility == Accessibility.Public)
			.Select(p => new PropertyToGenerate(
				Name: p.Name,
				Type: p.Type.ToDisplayString(),
				IsRequired: p.IsRequired
			))
			.ToList();

		return new TypeToGenerate(
			Namespace: targetType.ContainingNamespace.IsGlobalNamespace ? string.Empty : targetType.ContainingNamespace.ToDisplayString(),
			Name: targetType.Name,
			Properties: properties.ToEquatableReadOnlyList(),
			FakerName: symbol.Name
		);
	}

	[ExcludeFromCodeCoverage]
	private static TypeToGenerate? NoTypeToGenerate() => null;

	private static void Execute(SourceProductionContext context, TypeToGenerate typeToGenerate)
	{
		var w = new IndentedWriter();
		w.WriteLine(Header);
		w.WriteLine("#nullable enable");
		
		var fakerName = typeToGenerate.FakerName ?? $"{typeToGenerate.Name}Faker";
		
		if (!string.IsNullOrEmpty(typeToGenerate.Namespace))
		{
			w.WriteLine();
			w.WriteLine($"namespace {typeToGenerate.Namespace};");
		}

		w.WriteLine();
		w.WriteLine(Attributes);

		w.WriteLine($"public partial class {fakerName} : global::Forged.Core.Faker<{typeToGenerate.Name}>");
		w.BodyBlock(() => {

			foreach (var prop in typeToGenerate.Properties)
			{
				w.Write("public ");
				if (prop.IsRequired)
				{
					w.Write("required ");
				}
				w.Write($"virtual global::System.Func<global::Forged.Core.GenerationContext<{typeToGenerate.Name}>, global::Forged.Core.Generators.IGenerator<{prop.Type}>>");
				if (!prop.IsRequired)
				{
					w.Write("?");
				}
				w.WriteLine($" {prop.Name} {{ get; init; }}");
			}

			w.WriteLine();
			w.WriteLine("// Constructor");
			w.WriteLine($"public {fakerName}(global::System.Random? random = null, global::System.Globalization.CultureInfo? locale = null) : base(random, locale) {{ }}");

			w.WriteLine();
			w.WriteLine($"public override {typeToGenerate.Name} Get()");
			w.BodyBlock(() => {
				w.WriteLine("using var __forgedScope = base.Forge.BeginGeneration();");
				w.WriteLine();

				foreach (var prop in typeToGenerate.Properties)
				{
					w.Write($"var {Decapitalize(prop.Name)}Generator = {prop.Name}");
					w.WriteLine(prop.IsRequired
						? "(base.Context);"
						: "?.Invoke(base.Context);");
					w.WriteLine($"__forgedScope.Register<{prop.Type}>(nameof({prop.Name}), {Decapitalize(prop.Name)}Generator);");
				}

				w.WriteLine();
				w.WriteLine($"return new {typeToGenerate.Name}");
				w.InitBlock(() => {
					foreach (var prop in typeToGenerate.Properties)
					{
						w.WriteLine(prop.IsRequired
							? $"{prop.Name} = __forgedScope.Get<{prop.Type}>(nameof({prop.Name})),"
							: $"{prop.Name} = __forgedScope.GetOrDefault<{prop.Type}>(nameof({prop.Name})),");
					}
				});
			});
		});
		
		context.AddSource($"{fakerName}.g.cs", SourceText.From(w.ToString(), Encoding.UTF8));
	}

	private static void ExecuteGenerated(SourceProductionContext context, string modelNamespace, IReadOnlyList<TypeToGenerate> models)
	{
		var w = new IndentedWriter();
		w.WriteLine(Header);
		w.WriteLine("#nullable enable");

		if (!string.IsNullOrEmpty(modelNamespace))
		{
			w.WriteLine();
			w.WriteLine($"namespace {modelNamespace};");
		}

		w.WriteLine();
		w.WriteLine(Attributes);
		foreach (var model in models)
		{
			w.WriteLine($"public sealed class ForgedGenerated{model.Name}Values(global::Forged.Core.Forge forge)");
			w.BodyBlock(() => {
				foreach (var prop in model.Properties)
				{
					w.WriteLine($"public global::Forged.Core.Generators.Generator<{prop.Type}> {prop.Name}");
					w.WriteLine($"    => forge.Ref<{prop.Type}>(\"{prop.Name}\");");
				}
			});
			w.WriteLine();
		}

		w.WriteLine("public static class ForgedGeneratedContextExtensions");
		w.BodyBlock(() => {
			foreach (var model in models)
			{
				w.WriteLine($"extension(global::Forged.Core.GenerationContext<{model.Name}> context)");
				w.Block(() => {
					w.WriteLine($"public ForgedGenerated{model.Name}Values Generated => new(context.Forge);");
				});
			}
		});

		var hintName = string.IsNullOrEmpty(modelNamespace)
			? "ForgedGeneratedValues.g.cs"
			: $"ForgedGeneratedValues.{modelNamespace}.g.cs";
		context.AddSource(hintName, SourceText.From(w.ToString(), Encoding.UTF8));
	}

	private static string Decapitalize(string input)
	{
		var span = input.AsSpan();
		Span<char> result = stackalloc char[span.Length];
		result[0] = char.ToLowerInvariant(span[0]);
		span[1..].CopyTo(result[1..]);
		return result.ToString();
	}
}