using System.Globalization;

namespace Forged.Core.Generators.Utility.Text;

/// <summary>
/// Capitalizes the first character of strings generated by an inner generator.
/// </summary>
/// <param name="innerGenerator">The inner generator that produces strings.</param>
/// <param name="cultureInfo">The culture to use for capitalization. If null, uses invariant culture.</param>
/// <param name="rng">The random number generator to use (not used by this generator).</param>
public sealed class CapitalizeGenerator(Generator<string> innerGenerator, CultureInfo? cultureInfo, System.Random rng) : Generator<string>(rng)
{
	/// <summary>
	/// Generates a string with the first character capitalized.
	/// </summary>
	/// <returns>A string with the first character capitalized.</returns>
	public override string Generate()
	{
		var str = innerGenerator.Generate().AsSpan();
		Span<char> capitalized = [char.ToUpper(str[0], cultureInfo ?? CultureInfo.InvariantCulture), ..str[1..]];
		return capitalized.ToString();
	}
}
