using System.Globalization;

namespace Forged.Core.Generators.Utility.Text;

/// <summary>
/// Capitalizes the first character of strings generated by an inner generator.
/// </summary>
/// <param name="innerGenerator">The inner generator that produces strings.</param>
/// <param name="forge">The Forge instance to use.</param>
/// <param name="cultureInfo">The culture to use for capitalization. If null, uses the Forge's locale.</param>
public sealed class CapitalizeGenerator(Generator<string> innerGenerator, Forge forge, CultureInfo? cultureInfo = null) : Generator<string>(forge)
{
	/// <summary>
	/// Generates a string with the first character capitalized.
	/// </summary>
	/// <returns>A string with the first character capitalized.</returns>
	public override string Generate()
	{
		var str = innerGenerator.Generate().AsSpan();
		Span<char> capitalized = [char.ToUpper(str[0], cultureInfo ?? Locale), ..str[1..]];
		return capitalized.ToString();
	}
}
