namespace Forged.Core.Generators.Utility.Text;

/// <summary>
/// Converts strings generated by an inner generator to lowercase.
/// </summary>
/// <param name="innerGenerator">The inner generator that produces strings.</param>
/// <param name="forge">The Forge instance to use.</param>
public sealed class LowercaseGenerator(Generator<string> innerGenerator, Forge forge) : Generator<string>(forge)
{
	/// <summary>
	/// Generates a lowercase string.
	/// </summary>
	/// <returns>A lowercase string.</returns>
	public override string Generate() => innerGenerator.Generate().ToLowerInvariant();
}
