namespace Forged.Core.Generators.Utility.Text;

/// <summary>
/// Converts strings generated by an inner generator to lowercase.
/// </summary>
/// <param name="innerGenerator">The inner generator that produces strings.</param>
/// <param name="rng">The random number generator to use (not used by this generator).</param>
public sealed class LowercaseGenerator(Generator<string> innerGenerator, System.Random rng) : Generator<string>(rng)
{
	/// <summary>
	/// Generates a lowercase string.
	/// </summary>
	/// <returns>A lowercase string.</returns>
	public override string Generate() => innerGenerator.Generate().ToLowerInvariant();
}
