namespace Forged.Core.Generators.Utility.Text;

/// <summary>
/// Represents a generator that produces a substring of a specified range from a generated string value.
/// </summary>
/// <typeparam name="T">The type of the generated value, constrained to strings in this implementation. </typeparam>
/// <remarks>
/// The <c>RangeGenerator</c> class is a specialized generator for creating substrings from
/// the output of an inner <c>Generator&lt;string&gt;</c>. It takes a range specified by a starting index
/// and an optional ending index.
/// </remarks>
/// <exception cref="ArgumentOutOfRangeException">
/// Thrown if the specified range is outside the bounds of the string generated by the inner generator.
/// </exception>
/// <param name="innerGenerator">
/// The inner string generator whose output will be used to extract the range.
/// </param>
/// <param name="start">
/// The starting index of the substring within the string generated by the inner generator.
/// </param>
/// <param name="end">
/// The optional ending index of the substring within the generated string. If not supplied, the substring
/// will include characters up to the end of the inner-generator's output.
/// </param>
/// <param name="forge">
/// The <c>Forge</c> instance providing shared dependencies such as a random number generator
/// and locale information.
/// </param>
public sealed class RangeGenerator(Generator<string> innerGenerator, int start, int? end, Forge forge) : Generator<string>(forge)
{
	public override string Generate()
	{
		var str = innerGenerator.Generate().AsSpan();

		var newEnd = end ?? str.Length;

		if (start >= newEnd)
		{
			return string.Empty;
		}

		if (start > str.Length || newEnd > str.Length)
		{
			throw new ArgumentOutOfRangeException();
		}

		var s = start < 0 ? str.Length - start : start;
		var e = newEnd < 0 ? str.Length - newEnd : newEnd;

		return str[s..e].ToString();
	}
}