using System.Globalization;
using System.Text;
using Forged.Core.Core;

namespace Forged.Core.Generators.Utility.Text;

/// <summary>
/// Converts strings generated by an inner generator into properly formatted sentences.
/// </summary>
/// <param name="innerGenerator">The inner generator that produces strings.</param>
/// <param name="minSentenceLength">The minimum number of words per sentence.</param>
/// <param name="maxSentenceLength">The maximum number of words per sentence.</param>
/// <param name="forge">The Forge instance to use.</param>
/// <param name="cultureInfo">The culture to use for capitalization. If null, uses the Forge's locale.</param>
public sealed class SentencifyGenerator(
	Generator<string> innerGenerator,
	int minSentenceLength,
	int maxSentenceLength,
	Forge forge,
	CultureInfo? cultureInfo = null
) : Generator<string>(forge)
{
	/// <summary>
	/// Generates a string formatted as sentences.
	/// </summary>
	/// <returns>A string with proper sentence capitalization and punctuation.</returns>
	public override string Generate()
	{
		var str = innerGenerator.Generate().AsSpan();
		var words = str.Split(' ');

		var builder = new StringBuilder();
		
		var length = 0;
		foreach (var wordRange in words)
		{
			length++;
			var word = str[wordRange];

			if (length == 1)
			{
				Span<char> cap = [char.ToUpper(word[0], cultureInfo ?? Locale), ..word[1..]];
				builder.Append(cap);
				builder.Append(' ');
				continue;
			}
			
			if (length >= minSentenceLength && (length >= maxSentenceLength || Rng.Chance(0.15f)))
			{
				builder.Append(word);
				builder.Append('.');
				builder.Append(' ');
				length = 0;
				continue;
			}
			
			builder.Append(word);
			builder.Append(' ');
		}

		builder.Remove(builder.Length - 1, 1);

		if (builder[^1] != '.')
		{
			builder.Append('.');
		}
		
		return builder.ToString();
	}
}
