using System.Globalization;

namespace Forged.Core.Generators.Utility.Text;

/// <summary>
/// Converts strings generated by an inner generator to title case.
/// </summary>
/// <param name="innerGenerator">The inner generator that produces strings.</param>
/// <param name="cultureInfo">The culture to use for title case conversion. If null, uses invariant culture.</param>
/// <param name="rng">The random number generator to use (not used by this generator).</param>
public sealed class TitleCaseGenerator(Generator<string> innerGenerator, CultureInfo? cultureInfo, System.Random rng) : Generator<string>(rng)
{
	private readonly TextInfo _textInfo = cultureInfo?.TextInfo ?? CultureInfo.InvariantCulture.TextInfo;

	/// <summary>
	/// Generates a title case string.
	/// </summary>
	/// <returns>A title case string.</returns>
	public override string Generate() => _textInfo.ToTitleCase(innerGenerator.Generate());
}
