using System.Globalization;

namespace Forged.Core.Generators.Utility.Text;

/// <summary>
/// Converts strings generated by an inner generator to title case.
/// </summary>
/// <param name="innerGenerator">The inner generator that produces strings.</param>
/// <param name="forge">The Forge instance to use.</param>
/// <param name="cultureInfo">The culture to use for title case conversion. If null, uses the Forge's locale.</param>
public sealed class TitleCaseGenerator(Generator<string> innerGenerator, Forge forge, CultureInfo? cultureInfo = null) : Generator<string>(forge)
{
	private readonly TextInfo _textInfo = (cultureInfo ?? forge.Locale).TextInfo;

	/// <summary>
	/// Generates a title case string.
	/// </summary>
	/// <returns>A title case string.</returns>
	public override string Generate() => _textInfo.ToTitleCase(innerGenerator.Generate());
}
