namespace Forged.Core.Generators.Utility.Text;

/// <summary>
/// Converts values generated by an inner generator to their string representation.
/// </summary>
/// <typeparam name="T">The type to convert to string.</typeparam>
/// <param name="innerGenerator">The inner generator that produces values.</param>
/// <param name="forge">The Forge instance to use.</param>
public sealed class ToStringGenerator<T>(Generator<T> innerGenerator, Forge forge) : Generator<string?>(forge)
{
	/// <summary>
	/// Generates a string representation of the generated value.
	/// </summary>
	/// <returns>A string representation of the generated value, or null if the value is null.</returns>
	public override string? Generate() => innerGenerator.Generate()?.ToString();
}
