namespace Forged.Core.Generators.Utility.Text;

/// <summary>
/// Converts values generated by an inner generator to their string representation.
/// </summary>
/// <typeparam name="T">The type to convert to string.</typeparam>
/// <param name="innerGenerator">The inner generator that produces values.</param>
/// <param name="rng">The random number generator to use (not used by this generator).</param>
public sealed class ToStringGenerator<T>(Generator<T> innerGenerator, System.Random rng) : Generator<string?>(rng)
{
	/// <summary>
	/// Generates a string representation of the generated value.
	/// </summary>
	/// <returns>A string representation of the generated value, or null if the value is null.</returns>
	public override string? Generate() => innerGenerator.Generate()?.ToString();
}
