namespace Forged.Core.Generators.Utility.Text;

/// <summary>
/// Converts strings generated by an inner generator to uppercase.
/// </summary>
/// <param name="innerGenerator">The inner generator that produces strings.</param>
/// <param name="forge">The Forge instance to use.</param>
public sealed class UppercaseGenerator(Generator<string> innerGenerator, Forge forge) : Generator<string>(forge)
{
	/// <summary>
	/// Generates an uppercase string.
	/// </summary>
	/// <returns>An uppercase string.</returns>
	public override string Generate() => innerGenerator.Generate().ToUpperInvariant();
}
