namespace Forged.Core.Generators.Utility.Text;

/// <summary>
/// Converts strings generated by an inner generator to uppercase.
/// </summary>
/// <param name="innerGenerator">The inner generator that produces strings.</param>
/// <param name="rng">The random number generator to use (not used by this generator).</param>
public sealed class UppercaseGenerator(Generator<string> innerGenerator, System.Random rng) : Generator<string>(rng)
{
	/// <summary>
	/// Generates an uppercase string.
	/// </summary>
	/// <returns>An uppercase string.</returns>
	public override string Generate() => innerGenerator.Generate().ToUpperInvariant();
}
