namespace Forged.Core.Generators.Utility;

/// <summary>
/// A generator that caches the value generated by its inner generator during a single Generate() call.
/// </summary>
/// <typeparam name="T">The type of the generated value.</typeparam>
public sealed class MemoGenerator<T>(IGenerator<T> innerGenerator, Forge forge) : Generator<T>(forge)
{
	private T? _currentValue;

	public T CurrentValue => _currentValue!;

	public override T Generate()
	{
		_currentValue = innerGenerator.Generate();
		return _currentValue;
	}
}

/// <summary>
/// A generator that returns the cached value of an associated MemoGenerator.
/// </summary>
/// <typeparam name="T">The type of the generated value.</typeparam>
public sealed class MemoValueGenerator<T>(MemoGenerator<T> memoGenerator, Forge forge) : Generator<T>(forge)
{
	public override T Generate() => memoGenerator.CurrentValue;
}
