namespace Forged.Core.Generators.Utility;

/// <summary>
/// Generates values by transforming the output of an inner generator using a refiner function.
/// </summary>
/// <typeparam name="T">The type generated by the inner generator.</typeparam>
/// <typeparam name="TNew">The type produced by the refiner function.</typeparam>
/// <param name="innerGenerator">The inner generator whose output will be transformed.</param>
/// <param name="refiner">The function used to transform the inner generator's output.</param>
/// <param name="rng">The random number generator to use.</param>
public sealed class RefineGenerator<T, TNew>(Generator<T> innerGenerator, Func<T, TNew> refiner, System.Random rng) : Generator<TNew>(rng)
{
	/// <summary>
	/// Generates a value by first generating from the inner generator and then applying the refiner.
	/// </summary>
	/// <returns>The refined value.</returns>
	public override TNew Generate()
	{
		var value = innerGenerator.Generate();
		return refiner(value);
	}
}
