using Forged.Core.Generators;
using Forged.Core.Generators.Utility;
using Forged.Core.Generators.Utility.Collections;

namespace Forged.Core.Extensions;

/// <summary>
/// Extension methods for IEnumerable generators.
/// </summary>
public static class EnumerableGeneratorExtensions
{
	/// <summary>
	/// Converts enumerables from a generator to lists.
	/// </summary>
	/// <typeparam name="T">The type of items in the enumerable.</typeparam>
	/// <param name="generator">The generator to convert.</param>
	/// <returns>A generator that produces lists.</returns>
	public static Generator<List<T>> AsList<T>(this Generator<IEnumerable<T>> generator)
		=> new RefineGenerator<IEnumerable<T>, List<T>>(generator, static e => e.ToList(), generator.Forge);

	/// <param name="generator">The generator to convert.</param>
	/// <typeparam name="T">The type of items in the enumerable.</typeparam>
	extension<T>(Generator<IEnumerable<T>> generator)
	{
		/// <summary>
		/// Converts enumerables from a generator to dictionaries.
		/// </summary>
		/// <typeparam name="TKey">The type of dictionary keys.</typeparam>
		/// <typeparam name="TValue">The type of dictionary values.</typeparam>
		/// <param name="keySelector">A function to extract the key from each item.</param>
		/// <param name="valueSelector">A function to extract the value from each item.</param>
		/// <returns>A generator that produces dictionaries.</returns>
		public Generator<Dictionary<TKey, TValue>> AsDictionary<TKey, TValue>(Func<T, TKey> keySelector,
			Func<T, TValue> valueSelector
		) where TKey : notnull
			=> generator.Refine(e => e.ToDictionary(keySelector, valueSelector));
		
		/// <summary>
		/// Creates a generator that produces shuffled versions of the enumerable generated by the given generator.
		/// </summary>
		/// <typeparam name="T">The type of elements in the enumerable being shuffled.</typeparam>
		/// <returns>A generator that produces shuffled enumerables.</returns>
		public Generator<IEnumerable<T>> Shuffle()
			=> new ShuffleGenerator<T>(generator, generator.Forge);
		
		/// <summary>
		/// Converts enumerables from a generator to hash sets.
		/// </summary>
		/// <returns>A generator that produces hash sets.</returns>
		public Generator<HashSet<T>> AsHashSet()
			=> new RefineGenerator<IEnumerable<T>, HashSet<T>>(generator, static e => e.ToHashSet(), generator.Forge);
	}
}
